#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/clib/cjson.so \
	-O2 -fPIC src/strbuf.c src/lua_cjson.c src/fpconv.c -I../lua-headers \
	-Wall -pedantic -DDISABLE_INVALID_NUMBERS \
	-s -static-libgcc
