#!/bin/sh

gcc --version | grep gcc

cd "${0%build}" || exit 1

set -e
cd src/src || exit 1

export LUA_PATH_DEFAULT="!/../lua/?.lua"
export LUA_CPATH_DEFAULT="!/clib/?.so"

CFLAGS="-pthread -DCOUNTS \
	-msse4.2 \
	-DALLEGORY_BUILD \
	-DLUAJIT_ENABLE_GC64 \
	-DLUAJIT_ENABLE_LUA52COMPAT \
	-DLUA_PATH_DEFAULT='\"$LUA_PATH_DEFAULT\"' \
	-DLUA_CPATH_DEFAULT='\"$LUA_CPATH_DEFAULT\"' \
	-I. \
	"

LDFLAGS="-pthread -static-libgcc -Wl,--disable-new-dtags -Wl,-rpath,'\$\$ORIGIN'"

B=../../../../bin
J=$B/../lua/jit

rm -f $B/luajit
rm -f $B/libluajit.so

make clean
make HOST_CC=gcc amalg Q=" " \
	LDFLAGS="$LDFLAGS" \
	CFLAGS="$CFLAGS -DCOUNTS" \
	DASM_XFLAGS="$DASM_XFLAGS"

cp -f luajit $B/luajit
cp -f libluajit.so $B/libluajit.so

rm -rf $J/
mkdir -p $J
cp -f jit/*.lua $J/
rm $J/dis_arm*
rm $J/dis_mips*
rm $J/dis_ppc*

make clean
