#!/bin/sh
cd "${0%build}" || exit 1

files="
src/decNumber/decContext.c
src/decNumber/decNumber.c
src/decNumber/decPacked.c
src/decNumber/decimal128.c
src/decNumber/decimal32.c
src/decNumber/decimal64.c
src/ldecNumber.c
"

gcc -shared -o ../../bin/clib/ldecnumber.so \
	-O2 -fPIC $files -Isrc -Isrc/decNumber -I../lua-headers \
	-s -static-libgcc -L../../bin
