#!/bin/sh
cd "${0%build}" || exit 1

build() {
	gcc -shared -o ../../bin/libpillow_simd$S.so \
		-O3 -Isrc/src/libImaging -I. $C -fPIC \
		-DHAVE_PROTOTYPES \
		-DSTDC_HEADERS \
		-DSIZEOF_SHORT=2 \
		-DSIZEOF_INT=4 \
		-DSIZEOF_LONG=8 \
		-DSIZEOF_LONG_LONG=8 \
		src/src/libImaging/Resample.c \
		src/src/libImaging/Storage.c \
		src/src/libImaging/Copy.c \
		src/src/libImaging/Palette.c \
		Python.c \
		pillow_simd.c \
		-Wl,--version-script=pillow_simd.version -s -static-libgcc
}

C="-msse4.2"       build
C="-mavx2" S=_avx2 build
