#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 -fno-strict-aliasing $C mdbx_schema.c -Wall -I.
	${X}gcc *.o -shared -o ../../bin/$P/$D $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows L="-s -static-libgcc" D=mdbx_schema.dll A=mdbx_schema.a build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	P=osx C="-arch x86_64" L="-arch x86_64 -install_name @rpath/libmdbx_schema.dylib" \
	D=libmdbx_schema.dylib A=libmdbx_schema.a build
else
	P=linux C="-fPIC" L="-s -static-libgcc" D=libmdbx_schema.so A=libmdbx_schema.a build
fi
