#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/libbcrypt1.so -O2 -fPIC -fomit-frame-pointer -funroll-loops \
	src/crypt_blowfish.c src/crypt_gensalt.c src/wrapper.c -Isrc \
	-s -static-libgcc -Wl,--version-script=bcrypt.version
