#!/bin/bash
# dump symbols from dynamic libraries

LANG=C # for sort

DEF=d

usage() {
	echo
	echo " USAGE: syms [-d|-u|-l|-lu|-f] LIBNAME1|LIBFILE1.so ..."
	echo
	echo "   -d       dump defined symbols (default)"
	echo "   -u       dump undefined symbols"
	echo "   -l       dump dependent libraries"
	echo
	exit 1
}

[ -z "$1" ] && usage
if [ "x${1:0:1}" = "x-" ]; then
	if [ \
		"x$1" = "x-d" -o \
		"x$1" = "x-u" -o \
		"x$1" = "x-l" -o \
		"x$1" = "x-lu" -o \
		"x$1" = "x-f" \
	]; then
		DEF=${1:1}
		shift
	else
		usage
	fi
fi

# clean up a list of libs (remove prefix, suffix and implicit dependencies)
clean_libname() {
	while read s; do

		# show full-pathname deps as they are
		[ "${s#/}" = "$s" ] && {
			# filename -> libname
			s="$(echo "$s" | tr '[A-Z]' '[a-z]')"  # lowercase
			s=${s%.[0-9]*}                         # remove .major suffix (Linux)
			eval s=\$\{s#lib\}                     # remove platform-specific prefix
			eval s=\$\{s%.so\}                     # remove platform-specific suffix
		}

		# skip Linux implicit deps
		[ "$s" = "linux-vdso" ] && continue
		[[ "$s" == *"/ld-linux"* ]] && continue
		[ "$s" = "linux-gate" ] && continue

		# skip semi-implicit C runtime dep
		[ "$s" = "c" ] && continue

		echo "$s"
	done
}

syms_d_linux() { nm -gD --defined-only -f posix "$1" | cut -f1 -d' ' | sed 's/@.*//' | sort -u; }
syms_u_linux() { nm -gDu               -f posix "$1" | cut -f1 -d' ' | sed 's/@.*//' | sort -u; }
syms_l_linux() {
	ldd "$1" | cut -f1 -d' ' | clean_libname | sort
}
syms_one() {
	local fn="$1"
	local f="$fn"
	[ -f "$f" ] || f="bin/lib${fn}.so"
	[ -f "$f" ] || f="bin/clib/${fn}.so"
	syms_${DEF}_linux "$f"
}

while [ "$1" ]; do
	syms_one "$1"
	shift
done
