#!/bin/sh
cd "${0%build}" || exit 1

src_dir="$PWD/src"
B="$HOME/libjpegturbo-out"
rm -rf "$B"
mkdir -p "$B"
cd "$B" || exit 1
cmake -G "Unix Makefiles" "$src_dir"
make clean
make jpeg
strip "$B/libjpeg.so"
cp -f "$B/libjpeg.so" "$src_dir/../../../bin/libjpeg.so"
make clean
cd "$src_dir"
rm -rf "$B"
