#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/libblake3.so -fPIC -O3 -Wall -Wextra -std=c11 -pedantic -Isrc/c \
	src/c/blake3.c \
	src/c/blake3_dispatch.c \
	src/c/blake3_portable.c \
	src/c/blake3_sse2_x86-64_unix.S \
	src/c/blake3_sse41_x86-64_unix.S \
	src/c/blake3_avx2_x86-64_unix.S \
	src/c/blake3_avx512_x86-64_unix.S \
	-s -static-libgcc
