#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/libminizip2.so -msse3 -msse4.1 -O3 -fPIC -Isrc \
	-DHAVE_STDINT_H \
	-DHAVE_ZLIB \
	-DHAVE_WZAES \
	-DHAVE_PKCRYPT \
	-DMZ_ZIP_SIGNING \
	-DZLIB_COMPAT -I../zlib-ng/src -I../zlib-ng \
	src/mz_crypt.c \
	src/mz_os.c \
	src/mz_strm.c \
	src/mz_strm_buf.c \
	src/mz_strm_mem.c \
	src/mz_strm_pkcrypt.c \
	src/mz_strm_split.c \
	src/mz_strm_wzaes.c \
	src/mz_strm_zlib.c \
	src/mz_zip.c \
	src/mz_zip_rw.c \
	src/mz_crypt_openssl.c \
	src/mz_strm_os_posix.c \
	src/mz_os_posix.c \
	-L../../bin -lz -s -static-libgcc -Wl,--unresolved-symbols=report-all -lssl -lcrypto
