#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/libspng.so \
	-fPIC -U_FORTIFY_SOURCE -O3 -DSPNG_SSE=4 src/spng/*.c premultiply.c -Isrc/spng \
	-DZLIB_COMPAT -I../zlib-ng/src -I../zlib-ng \
	-L../../bin -lz -s -static-libgcc
