#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/libxxhash.so -O3 -fPIC -DXXH_SSE2 -msse2 src/*.c -Isrc \
	-std=c99 -Wall -Wextra -Wshadow -Wcast-qual -Wcast-align \
	-Wstrict-prototypes -Wstrict-aliasing=1 -Wswitch-enum -Wundef -pedantic \
	-s -static-libgcc
